print(' ')
print('------- Exercício 004 -------')
var = input('Digite algo: ')
print('O tipo primitivo desse valor é: {}'.format(type(var)))
print('Só tem espaços? ', var.isspace())
print('É um número? ', var.isnumeric())
print('É alfabético? ', var.isalpha())
print('É alfanumérico? ', var.isalnum())
print('Está em maiúsculo? ', var.isupper())
print('Está em minúsculo? ', var.islower())
print('Está em capitalizada? ', var.istitle())
print( )
print('------- DESAFIO 04 -------')
var = input('Digite algo: ')
print('Verificação se o que foi digitado é Alfabético:')
print(var.isalpha())
print('Verificação se o que foi digitado é Numerico:')
print(var.isnumeric())
print('Verificação se o que foi digitado é Alfanumérico:')
print(var.isalnum())
print(type(var))
